- hosts: localhost
  connection: local
  gather_facts: no           
  become: no
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  roles:
    - fonts
    - homebrew
    - homebrew-cask
    # - ruby-build
    - nodebrew
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    nodebrew_dir:
      - { name: '.nodebrew' }
      - { name: '.nodebrew/src' }
    homebrew_taps:
      # - homebrew/binary
      # - homebrew/dupes
      # - caskroom/cask
      # - caskroom/versions
      - homebrew/cask
      - homebrew/cask-versions
      - homebrew/cask-fonts
    homebrew_packages:
      - { name: openssl }
      # - { name: openssl, state: linked, install_options: force }
      - { name: python }
      - { name: ansible }
      - { name: git }
      - { name: nodebrew }
      - { name: readline }
      - { name: rbenv }
      - { name: ruby-build }
      - { name: imagemagick }
      - { name: optipng }
      - { name: wp-cli }
      - { name: composer }
      - { name: ffmpeg }
      - { name: jq }
      - { name: rename }
    # homebrew_cask_repositories:
    #   - caskroom/versions
    homebrew_cask_packages:
      - { name: iterm2 }
      - { name: firefox }
      - { name: google-chrome }
      - { name: microsoft-edge }
      # - { name: java }
      - { name: skype }
      # - { name: alfred2 }
      - { name: alfred }
      # - { name: sublime-text2 }
      - { name: sublime-text }
      - { name: evernote }
      - { name: dropbox }
      # - { name: filezilla }
      - { name: vagrant }
      - { name: virtualbox }
      - { name: kindle }
      # - { name: libreoffice }
      - { name: mamp }
      - { name: visual-studio-code }
      - { name: handbrake }
      - { name: blender }
      - { name: keyboardcleantool }
      - { name: karabiner-elements }
      - { name: notion }
      - { name: warp }
      # fonts / https://github.com/Homebrew/homebrew-cask-fonts/tree/master/Casks
      - { name: font-noto-sans-cjk-jp }
      - { name: font-noto-sans-javanese }
      - { name: font-noto-serif-cjk-jp }
      - { name: font-cardo }
      # - { name: font-cormorant-garamond }
      - { name: font-krona-one }
      - { name: font-overpass }
      - { name: font-inter }
      - { name: font-lobster }
      - { name: font-barlow }
      # - { name: font-montserrat }
      # - { name: font-roboto }
      # - { name: font-roboto-condensed }
      - { name: font-fontawesome }
      # - { name: font-klee-one }
    rbenv_global_gems:
      - compass
    # npm_global_packages_sudo:
    #   - grunt-cli
    npm_global_packages_user:
      # - grunt-cli
      - gulp-cli
      - bower
      - npm-check-updates
  # tasks:
  #   - name: homebrew の tap リポジトリを追加
  #     homebrew_tap: tap={{ item }} state=present
  #     with_items: "{{ homebrew_taps }}"

  #   - name: homebrew をアップデート
  #     homebrew: update_homebrew=yes

  #   # brew
  #   - name: brew パッケージをインストール
  #     homebrew:
  #       name: "{{ item.name }}"
  #       state: "{{ item.state | default('latest') }}"
  #       install_options: "{{ item.install_options | default('') }}"
  #     with_items: "{{ homebrew_packages }}"

  #   # cask
  #   - name: cask パッケージをインストール
  #     homebrew_cask: name={{ item.name }} state="present"
  #     with_items: "{{ homebrew_cask_packages }}"
  #     register: cask_result
