---

- name: nodebrewインストール用ディレクトリの存在チェック
  stat:
    path: "{{ home_dir }}/{{ nodebrew_dir }}"
  register: nb_directory_created

- name: nodebrewインストール用ディレクトリ作成
  file: 
    path: "{{ home_dir }}/{{ item.name }}"
    state: directory
    mode: 0755
  when: not nb_directory_created.stat.exists
  with_items: "{{ nodebrew_dir }}"

- name: node.jsがインストール済みかどうかを確認	
  shell: which node
  ignore_errors: True
  changed_when: False
  register: nodejs_installed

- name: インストール済みのnode.jsのバージョンを確認
  shell: nodebrew ls
  ignore_errors: True
  changed_when: False
  when: nodejs_installed is success
  register: nodejs_target_version_exist

- name: node.jsをインストール
  shell: nodebrew install-binary stable
  when: (nodejs_installed is failed) or (nodejs_target_version_exist is failed) 

- name: 使用するnode.jsのバージョンを指定
  shell: nodebrew use stable
  when: (nodejs_installed is failed) or (nodejs_target_version_exist is failed)

- name: npm update
  shell: npm update -g npm
  when: nodebrew_npm_update == True

# エラーが起こるため保留
# - name: npmグローバルインストール（sudo） 
#   npm: name={{ item }} state=latest global=yes
#   become: yes
#   with_items: "{{ npm_global_packages_sudo }}"

- name: npmグローバルインストール 
  npm: name={{ item }} state=latest global=yes
  with_items: "{{ npm_global_packages_user }}"