---
- name: homebrew の tap リポジトリを追加
  homebrew_tap: tap={{ item }} state=present
  with_items: "{{ homebrew_taps }}"

- name: homebrew をアップデート
  homebrew: update_homebrew=yes

# brew
- name: brew パッケージをインストール
  homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state | default('latest') }}"
    install_options: "{{ item.install_options | default('') }}"
  with_items: "{{ homebrew_packages }}"
  when: homebrew_packages|length > 0
# - name: homebrew の tap リポジトリを追加
#   homebrew_tap: tap={{ item }} state=present
#   with_items: "{{ homebrew_taps }}"

# - name: homebrew をアップデート
#   homebrew: update_homebrew=yes

# # brew
# - name: brew パッケージをインストール
#   homebrew:
#     name: "{{ item.name }}"
#     state: "{{ item.state | default('latest') }}"
#     install_options: "{{ item.install_options | default('') }}"
#   with_items: "{{ homebrew_packages }}"